// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4B-Z5nDVZ2Gc15z04uR5BtR6sQOIrkOc',
    appId: '1:826745105225:web:50fdba2df657dcd4838898',
    messagingSenderId: '826745105225',
    projectId: 'democra-sync',
    authDomain: 'democra-sync.firebaseapp.com',
    storageBucket: 'democra-sync.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzSQcO8RHzWxmIcDgi_LC5PxYgr5NEEUM',
    appId: '1:826745105225:android:f4e2f96a3b662360838898',
    messagingSenderId: '826745105225',
    projectId: 'democra-sync',
    storageBucket: 'democra-sync.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHLJYTw6fwjeSwi-8zMAhGlkrHEM18t18',
    appId: '1:826745105225:ios:e4198b3619aaa956838898',
    messagingSenderId: '826745105225',
    projectId: 'democra-sync',
    storageBucket: 'democra-sync.firebasestorage.app',
    iosBundleId: 'com.example.nemsuVoting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHLJYTw6fwjeSwi-8zMAhGlkrHEM18t18',
    appId: '1:826745105225:ios:e4198b3619aaa956838898',
    messagingSenderId: '826745105225',
    projectId: 'democra-sync',
    storageBucket: 'democra-sync.firebasestorage.app',
    iosBundleId: 'com.example.nemsuVoting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4B-Z5nDVZ2Gc15z04uR5BtR6sQOIrkOc',
    appId: '1:826745105225:web:e5cdfbd09303126c838898',
    messagingSenderId: '826745105225',
    projectId: 'democra-sync',
    authDomain: 'democra-sync.firebaseapp.com',
    storageBucket: 'democra-sync.firebasestorage.app',
  );
}
